#pragma once

enum State {
  INIT,
  CHOOSECOLOR,
  CHOOSEDIFFICULTY,
  INGAME,
  PLAYERMOVE,
  AIMOVE,
  GAMEOVER
};

enum ColorSelection { MCUMAX_BOARD_WHITE, MCUMAX_BOARD_BLACK };

enum PlayerMoveSelection { FROMROW, FROMCOL, TOROW, TOCOL };
